apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: tempus
  name: tempus
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: tempus
    spec:
      containers:
      - image: gcr.io/<My Project ID>/tempus:v0.4
        name: tempus
